migrate(
  (app) => {
    const collection = new Collection({
      name: "auditlog",
      type: "base",
      listRule: "",
      viewRule: "",
      createRule: null,
      updateRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          help: "",
          hidden: false,
          id: "text_pk_auditlog",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text_collection",
          max: 0,
          min: 0,
          name: "collection",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text_record",
          max: 0,
          min: 0,
          name: "record",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text_event",
          max: 0,
          min: 0,
          name: "event",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          collectionId: "_pb_users_auth_",
          collectionName: "users",
          cascadeDelete: false,
          help: "",
          hidden: false,
          id: "relation_user",
          maxSelect: 1,
          name: "user",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "relation",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text_admin",
          max: 0,
          min: 0,
          name: "admin",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          help: "",
          hidden: false,
          id: "json_data",
          maxSize: 5242880,
          name: "data",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "json",
        },
        {
          help: "",
          hidden: false,
          id: "json_original",
          maxSize: 5242880,
          name: "original",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "json",
        },
        {
          hidden: false,
          id: "autodate_created",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: true,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate_updated",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: true,
          type: "autodate",
        },
      ],
      indexes: [
        "CREATE INDEX `idx_auditlog_collection_record` ON `auditlog` (collection,record)",
        "CREATE INDEX `idx_auditlog_event` ON `auditlog` (event)",
      ],
      options: {},
    });

    app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("auditlog");
    app.delete(collection);
  },
);
